{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set version = data.get('version') %}

package:
    name: access-moppy-suite
    version: "{{ version }}"

source:
    url: "https://files.pythonhosted.org/packages/source/a/access_moppy/access_moppy-{{ version }}.tar.gz"

build:
    noarch: python
    number: 0

requirements:
    host:
        - python
        - pip
        - versioneer

outputs:
    - name: access-moppy
      build:
          noarch: python
      script: build_access_moppy.sh
      requirements:
          host:
              - python
              - pip
              - versioneer
          run:
              - python >=3.11,<3.14
              - numpy
              - pandas
              - xarray
              - netcdf4
              - cftime
              - dask
              - distributed >=2024.0.0
              - pyyaml
              - tqdm
              - requests
              - parsl
              - jinja2
      about:
          home: https://github.com/ACCESS-NRI/ACCESS-MOPPy
          license: Apache-2.0
          license_family: APACHE
          summary: 'ACCESS-MOPPy post-process ACCESS raw model output using CMOR and pre-defined data standards'

    - name: access-moppy-esmval
      build:
          noarch: python
      requirements:
          run:
              - {{ pin_subpackage('access-moppy', exact=True) }}
              - esmvalcore >=2.14
      about:
          home: https://github.com/ACCESS-NRI/ACCESS-MOPPy
          license: Apache-2.0
          license_family: APACHE
          summary: 'ACCESS-MOPPy with ESMValTool integration support'

extra:
    recipe-maintainers:
        - rbeucher
